apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-frontend"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        process: nginx
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80