TICKET_CREATED = 'created'
TICKET_UPDATED = 'updated'
TICKET_ASSIGNED = 'assigned'
TICKET_UNASSIGNED = 'unassigned'
TICKET_REASSIGNED = 'reassigned'
TICKET_STARTED = 'started'
TICKET_COMPLETED = 'completed'
TICKET_VERIFIED = 'verified'

ALL_EVENTS = [
    TICKET_CREATED,
    TICKET_UPDATED,
    TICKET_ASSIGNED,
    TICKET_UNASSIGNED,
    TICKET_REASSIGNED,
    TICKET_STARTED,
    TICKET_COMPLETED,
    TICKET_VERIFIED,
]