apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-backend"
  labels:
    app: backend
    process: daphne
    release: {{ .Release.Name }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: "http"
  selector:
    app: backend
    process: daphne
    release: {{ .Release.Name }}